### ISSUE TITLE
hardcoded local deps 

### ISSUE THREAD

**Issue by dcsan** [sayawan/flowwy#1]
looks like you have some local paths hardcoded into the `smart.require`

```
    "famodev": {
        "path": "/Users/rubyist/meteor/packages/famodev/src"
    }
```

```
=> Started proxy.                             
=> Meteor 1.1.0.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
   Building the application                  \
Ensure dependencies...
 Famono:  git update "famous" is up-to-date
 Famono:  git update "famous.polyfills" is up-to-date
 Famono:  git update "library" is up-to-date
 Famono:  Library created for "famous-polyfills" via alias
 Famono:  git update "flex" is up-to-date
=> Errors prevented startup:                  

   While building the application:
   fs.js:696:18: ENOENT, no such file or directory
   '/Users/rubyist/meteor/packages/famodev/src' (compiling lib/smart.require)
   at Object.fs.statSync (fs.js:696:18)
   at Object.sourceFetchers.path
   (packages/compileRequirejs/compile_requirejs.js:1102:1)
   at checkLibrarySource
   (packages/compileRequirejs/compile_requirejs.js:1292:1)
   at ensureDependencies
   (packages/compileRequirejs/compile_requirejs.js:1495:1)
   at Package (packages/compileRequirejs/compile_requirejs.js:2661:1)


=> Your application has errors. Waiting for file change.

```

**Comment by dcsan** [comment]
so i sent a PR to fix that issue but now i get this:

```
➜  flowwy git:(master) ✗ meteor
[[[[[ ~/dev/ref/flowwy ]]]]]                  

=> Started proxy.                             
=> Meteor 1.1.0.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
   Building the application                  -
Ensure dependencies...
 Famono:  git update "famous" is up-to-date
 Famono:  git update "famous.polyfills" is up-to-date
 Famono:  git update "library" is up-to-date
 Famono:  The alias for "famous-polyfills" is up-to-date
 Famono:  git update "flex" is up-to-date
 Famono:  git update "famodev" is up-to-date

/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
TypeError: Cannot call method 'split' of undefined
    at Object.exports.parse (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/parse-stack.js:18:26)
    at Object.exception (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:478:28)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/compiler.js:768:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at compileUnibuild (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/compiler.js:338:5)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/compiler.js:136:26
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compiler.compile (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/compiler.js:132:5)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:2090:24
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:245:19)
    at Object.exports.bundle (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:2040:31)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:554:24
    at time (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/profile.js:232:28)
    at Function.run (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/profile.js:378:12)
    at bundleApp (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:544:34)
    at [object Object]._.extend._runOnce (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:591:35)
    at [object Object]._.extend._fiber (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:821:28)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:402:12
```

any ideas?

**Comment by dcsan** [comment]
FYI same problem after updating:

```
meteor update

Changes to your project's package version selections from updating the release:

autoupdate          upgraded from 1.2.0 to 1.2.1
blaze               upgraded from 2.1.0 to 2.1.2
meteor              upgraded from 1.1.5 to 1.1.6
minifiers           upgraded from 1.1.4 to 1.1.5
minimongo           upgraded from 1.0.7 to 1.0.8
observe-sequence    upgraded from 1.0.5 to 1.0.6
spacebars-compiler  upgraded from 1.0.5 to 1.0.6
templating          upgraded from 1.1.0 to 1.1.1
tracker             upgraded from 1.0.6 to 1.0.7

flowwy: updated to Meteor 1.1.0.2.            

Changes to your project's package version selections from updating package versions:

coffeescript             added, version 1.0.6 
cosmos:browserify        added, version 0.1.4
meteorhacks:flow-router  upgraded from 1.1.1 to 1.7.0

➜  flowwy git:(issue1-hardwired-deps) ✗ meteor
[[[[[ ~/dev/ref/flowwy ]]]]]                  

=> Started proxy.                             
=> Started MongoDB.                           
   Building the application                  |
Ensure dependencies...

/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
TypeError: Cannot call method 'split' of undefined
    at Object.exports.parse (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/parse-stack.js:18:26)
    at Object.exception (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:478:28)
    at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/compiler.js:778:20
```

**Comment by dcsan** [comment]
with your fork of the repo, same issues

```
➜  flowwy git:(issue1-hardwired-deps) ✗ meteor
[[[[[ ~/dev/ref/flowwy ]]]]]                  

=> Started proxy.                             
=> Started MongoDB.                           
   Building the application                  |
Ensure dependencies...
 Famono:  git update "famous" is up-to-date
 Famono:  git update "famous.polyfills" is up-to-date
 Famono:  git update "library" is up-to-date
 Famono:  The alias for "famous-polyfills" is up-to-date
 Famono:  git update "flex" is up-to-date
 Famono:  Could not find repo for "famodev", please set "git"/"bower"/"alias"/"http"/"path"

/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
TypeError: Cannot call method 'split' of undefined
    at Object.exports.parse (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/parse-stack.js:18:26)
    at Object.exception (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:478:28)
    at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/compiler.js:778:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at compileUnibuild (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/compiler.js:338:5)
    at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/compiler.js:136:26
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compiler.compile (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/compiler.js:132:5)
    at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:2090:24
    at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:245:19)
    at Object.exports.bundle (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:2040:31)
    at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:554:24
    at time (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/profile.js:231:28)
    at Function.run (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/profile.js:377:12)
    at bundleApp (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:544:34)
    at [object Object]._.extend._runOnce (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:591:35)
    at [object Object]._.extend._fiber (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:821:28)
    at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:402:12
➜  flowwy git:(issue1-hardwired-deps) ✗ tail lib/smart.require 
    },
    "flex": {
        "git": "https://github.com/IjzerenHein/famous-flex.git",
        "root": "src"
    },
    "famodev": {
    "src": "https://github.com/sayawan/famodev.git",
    "root": "src"
    }
}%                                         

```
