### ISSUE TITLE
removed flex but still get errors

### ISSUE THREAD

**Issue by dcsan** [sayawan/flowwy#3]
this was causing a weird 'split' error

```
    "flex": {
        "git": "https://github.com/IjzerenHein/famous-flex.git",
        "root": "src"
    },
```

now i get this

```
meteor
[[[[[ ~/dev/ref/flowwy ]]]]]                  

=> Started proxy.                             
=> Meteor 1.1.0.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
   Building the application                  |
Ensure dependencies...
 Famono:  git update "famous" is up-to-date
 Famono:  git update "famous.polyfills" is up-to-date
 Famono:  git update "library" is up-to-date
 Famono:  The alias for "famous-polyfills" is up-to-date
 Famono:  remove dep "flex" /Users/dc/dev/ref/flowwy/.meteor/.famono-repos/flex
 Famono:  git update "famodev" is up-to-date
 Famono:  Warning, could not load library "famodev/Node" file: /Users/dc/dev/ref/flowwy/src/Each
 Famono:  Warning, could not load library "famodev/Modifier" file: /Users/dc/dev/ref/flowwy/src/Each
 Famono:  Warning, could not load library "famodev/reactive/ReactiveCursor" file: /Users/dc/dev/ref/flowwy/src/Each
 Famono:  Warning, could not load library "famodev/reactive/ReactiveSession" file: /Users/dc/dev/ref/flowwy/src/ReactiveSurface
I20150516-15:26:04.840(-7)? hello webstorm    
W20150516-15:26:04.842(-7)? (STDERR) 
W20150516-15:26:04.842(-7)? (STDERR) /Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150516-15:26:04.842(-7)? (STDERR)                        throw(ex);
W20150516-15:26:04.843(-7)? (STDERR)                              ^
W20150516-15:26:04.843(-7)? (STDERR) Error: Famous "define" cannot run on the server
W20150516-15:26:04.843(-7)? (STDERR)     at global.define (packages/raix:famono/requirejs_server.js:7:1)
W20150516-15:26:04.843(-7)? (STDERR)     at app/src/Each.js:10:1
W20150516-15:26:04.843(-7)? (STDERR)     at app/src/Each.js:213:3
W20150516-15:26:04.843(-7)? (STDERR)     at /Users/dc/dev/ref/flowwy/.meteor/local/build/programs/server/boot.js:222:10
W20150516-15:26:04.843(-7)? (STDERR)     at Array.forEach (native)
W20150516-15:26:04.843(-7)? (STDERR)     at Function._.each._.forEach (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150516-15:26:04.844(-7)? (STDERR)     at /Users/dc/dev/ref/flowwy/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
   Building the application                  |
Ensure dependencies...
I20150516-15:26:07.506(-7)? hello webstorm    
W20150516-15:26:07.507(-7)? (STDERR) 
W20150516-15:26:07.507(-7)? (STDERR) /Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150516-15:26:07.507(-7)? (STDERR)                        throw(ex);
W20150516-15:26:07.507(-7)? (STDERR)                              ^
W20150516-15:26:07.513(-7)? (STDERR) Error: Famous "define" cannot run on the server
W20150516-15:26:07.513(-7)? (STDERR)     at global.define (packages/raix:famono/requirejs_server.js:7:1)
W20150516-15:26:07.513(-7)? (STDERR)     at app/src/Each.js:10:1
W20150516-15:26:07.513(-7)? (STDERR)     at app/src/Each.js:213:3
W20150516-15:26:07.513(-7)? (STDERR)     at /Users/dc/dev/ref/flowwy/.meteor/local/build/programs/server/boot.js:222:10
W20150516-15:26:07.513(-7)? (STDERR)     at Array.forEach (native)
W20150516-15:26:07.513(-7)? (STDERR)     at Function._.each._.forEach (/Users/dc/.meteor/packages/meteor-tool/.1.0.45.1rbfldw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150516-15:26:07.514(-7)? (STDERR)     at /Users/dc/dev/ref/flowwy/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
                                             |
Ensure dependencies...
^C                                            
➜  flowwy git:(master) ✗ 
```

**Comment by dcsan** [comment]
looks like famodev got pulled into this app but the directory structure is different

```
 Famono:  Warning, could not load library "famodev/Node" file: /Users/dc/dev/ref/flowwy/src/Each
 Famono:  Warning, could not load library "famodev/Modifier" file: /Users/dc/dev/ref/flowwy/src/Each
 Famono:  Warning, could not load library "famodev/reactive/ReactiveCursor" file: /Users/dc/dev/ref/flowwy/src/Each
 Famono:  Warning, could not load library "famodev/reactive/ReactiveSession
```

![image](https://cloud.githubusercontent.com/assets/514002/7668212/49b0aa48-fbe0-11e4-9941-3f8ed20efc64.png)
