### ISSUE TITLE
build fails with latest flex layout

### ISSUE THREAD

**Issue by dcsan** [sayawan/flowwy#5]
using current master from famous-flex project will crash.
placeholder ticket to ask that team for suggestions too

```
bin/run.sh 
[[[[[ ~/dev/ref/flowwy-dcsan/app ]]]]]        

=> Started proxy.                             
=> Started MongoDB.                           
   Building the application                  \
Ensure dependencies...

/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
TypeError: Cannot call method 'split' of undefined
  at Object.exports.parse (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/parse-stack.js:18:26)
  at Object.exception (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:478:28)
  at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/compiler.js:778:20
  at Array.forEach (native)
  at Function._.each._.forEach (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at compileUnibuild (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/compiler.js:338:5)
  at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/compiler.js:136:26
  at Array.forEach (native)
  at Function._.each._.forEach (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at Object.compiler.compile (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/compiler.js:132:5)
  at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:2090:24
  at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:264:13
  at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
  at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:257:29
  at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
  at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:255:18
  at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
  at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:246:23
  at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
  at Object.capture (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:245:19)
  at Object.exports.bundle (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:2040:31)
  at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:554:24
  at time (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/profile.js:231:28)
  at Function.run (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/profile.js:377:12)
  at bundleApp (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:544:34)
  at [object Object]._.extend._runOnce (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:591:35)
  at [object Object]._.extend._fiber (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:821:28)
  at /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:402:12

```

**Comment by dcsan** [comment]
tracking https://github.com/IjzerenHein/famous-flex/issues/103
